### PR TITLE
Update dependency versions

### PR DESCRIPTION
**Pull request by jrmhaig**
I have closed the original pull requests (#22) and opened an identical one from a branch as I want to work on the master of my fork. The comments from the original PR are:

---

Note, I have not extensively tested this but I have managed to `bundle install` and run the example `bundle exec bin/rtanque start sample_bots/keyboard.rb sample_bots/seek_and_destroy.rb`.

Currently, RTanque only works for Ruby <= 2.0 but the oldest currently supported version of Ruby is 2.2 (2.1 will cease getting security patches after March 2017).

It appears that the problem is with the `gosu` and `texplay` gems as the versions specified in the gemspec file will not compile. I have been able to install the latest version of `gosu`, 0.10.8. For `texplay`, however, the pre-release of 0.4.4 is the only version that will compile.

Tested on Mac 10.9.5 and Ubuntu 16.04.

---

I have updated the Travis files:
* Added Ruby 2.1.0, 2.2.0 and 2.3.0 (Maybe 2.4.0 should be added too?).
* Fixed rspec to version 2. There are important breaking changes in version 3.

### CODE REVIEW

**Comment by awilliams** [comment]
Thanks for the PR. I've added you as a contributor to this repo since I don't have much time to dedicate to this project. I couldn't find a way to message you directly beforehand to ask if you were interested, so please ignore if you're not.

**Comment by jrmhaig** [comment]
Thank you. If I may I will leave the invite to be a contributor unanswered for the moment. In the short term I am not intending to make significant contributions but rather to try a few things out. Of course, if my experiments are successful they may feed back but I don't want to start doing something and then leave it incomplete.

Specifically (in case you are interested) I am thinking of splitting the gem into a 'core' component and a 'gosi' component, with the idea that other front ends can be added. This is so that I can then create a web version.

**Comment by jrmhaig** [comment]
Hi again. I have updated this PR with newer versions of the gems and I intend to merge it, having now accepted your invitation to collaborate with the repository. However, I do not think I can update the gem on Rubygems. Are you able to do that? Or possibly give me access?

**Comment by awilliams** [comment]
Thanks @jrmhaig for all your work. I've added you as an owner on [rubygems.org](https://rubygems.org/gems/rtanque), which should allow you to update the gem. Please let me know if this did not work.

**Pull request merged**
